// Hand-curated keyword lists for Cambridge IGCSE Physics 0625's six
// syllabus topics. This is a deliberate scoping choice, not a placeholder:
// `SyllabusOverview` only extracts topic names (see syllabus-extraction's
// documented limitation — the full topic -> sub-topic -> learning-objective
// hierarchy isn't parsed yet), so there is no extracted text to derive
// keywords from. Curating them by hand is the deterministic option
// available today; once the full hierarchy or Phase 5 embeddings exist,
// this table can be replaced with something derived rather than typed in.
//
// Subject-specific by design — do not generalize to other subjects until a
// second subject's keyword list actually exists (see
// docs/BEST-CODING_PRACTICES.md on avoiding premature generalization).
export const PHYSICS_0625_TOPIC_KEYWORDS: Record<string, string[]> = {
  'Motion, forces and energy': [
    'speed',
    'velocity',
    'acceleration',
    'distance-time',
    'speed-time',
    'mass',
    'weight',
    'density',
    'resultant force',
    'newton',
    'momentum',
    'moment',
    'pressure',
    'work done',
    'kinetic energy',
    'potential energy',
    'gravitational',
    'power',
    'efficiency',
    'hooke',
    'spring',
    'elastic',
    'scalar',
    'vector',
  ],
  'Thermal physics': [
    'particle',
    'kinetic particle theory',
    'brownian motion',
    'solid',
    'liquid',
    'gas',
    'evaporation',
    'condensation',
    'melting',
    'boiling',
    'freezing',
    'thermal expansion',
    'specific heat capacity',
    'specific latent heat',
    'conduction',
    'convection',
    'thermal radiation',
    'infrared',
    'temperature',
    'thermometer',
    'absolute zero',
    'kelvin',
  ],
  Waves: [
    'wave',
    'wavelength',
    'frequency',
    'amplitude',
    'wave speed',
    'transverse',
    'longitudinal',
    'reflection',
    'refraction',
    'diffraction',
    'lens',
    'converging',
    'diverging',
    'principal axis',
    'principal focus',
    'real image',
    'virtual image',
    'critical angle',
    'total internal reflection',
    'electromagnetic spectrum',
    'ultraviolet',
    'x-ray',
    'microwave',
    'sound wave',
    'echo',
    'ultrasound',
  ],
  'Electricity and magnetism': [
    'current',
    'charge',
    'coulomb',
    'circuit',
    'resistor',
    'resistance',
    'potential difference',
    'voltage',
    'e.m.f.',
    'electromotive force',
    'ammeter',
    'voltmeter',
    'series circuit',
    'parallel circuit',
    'magnetic field',
    'magnet',
    'electromagnet',
    'solenoid',
    'transformer',
    'generator',
    'electric motor',
    'induction',
    'static electricity',
    'insulator',
    'conductor',
    'fuse',
  ],
  'Nuclear physics': [
    'atom',
    'nucleus',
    'nuclide',
    'proton',
    'neutron',
    'electron',
    'isotope',
    'radioactive',
    'radioactivity',
    'radiation',
    'alpha',
    'beta',
    'gamma',
    'half-life',
    'nuclear equation',
    'decay',
    'nuclear fission',
    'nuclear fusion',
    'geiger',
  ],
  'Space physics': [
    'earth',
    'sun',
    'moon',
    'solar system',
    'planet',
    'orbit',
    'satellite',
    'star',
    'galaxy',
    'universe',
    'light-year',
    'red-shift',
    'big bang',
    'gravitational field',
  ],
}
